version: '3.8'
services:
  apiserver:
    image: kirandockerwhale/complex-fibonacci-server:${IMAGE_TAG}
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}

  client:
    image: kirandockerwhale/complex-fibonacci-client:${IMAGE_TAG}

  nginx:
    image: kirandockerwhale/complex-fibonacci-nginx:${IMAGE_TAG}
    ports:
      - "80:80"

  worker:
    image: kirandockerwhale/complex-fibonacci-worker:${IMAGE_TAG}
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}