version: '3.8'
services:
  apiserver:
    image: kirandockerwhale/complex-fibonacci-server:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: 5432
    depends_on:
      - redis
      - postgres

  client:
    image: kirandockerwhale/complex-fibonacci-client:latest

  nginx:
    image: kirandockerwhale/complex-fibonacci-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - apiserver

  worker:
    image: kirandockerwhale/complex-fibonacci-worker:latest
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
    depends_on:
      - redis
      - postgres